### ISSUE TITLE
Can I do everything with one ESP32?

### ISSUE THREAD

**Issue by mnltake** [doppelgrau/esp32-f9p-io-board#15]
Hello doppelgrau.
It is a wonderful work!
I want to use this board for NTRIP Client to F9P, and AutoSteer to AgOpenGPS .
Do you think it is possible in ONE esp32?

**Comment by doppelgrau** [comment]
Yes, that should be no problem.
See https://github.com/eringerli/esp32-aog
I plan to port it to the pcb (support ethernet, the port expander, VNH7070, LSM9DS1, ...), but I guess combining the arduino scatches from @Coffeetrac would work, too.
