### ISSUE TITLE
C35 Capacitance Value

### ISSUE THREAD

**Issue by mnltake** [doppelgrau/esp32-f9p-io-board#16]
Thank you for answering my question!
I noticed a small point.

In the circuit diagram "C35" is "100nF/16V" 
But in "Parts.ods" C35's Mouser Partnumber is "603-CC805KRX7R9BB103"
it's 10nF.

I think Row"C35,C47,D2,D5,D9"   Colum"Mouser Partnumber-" is wrong.

**Comment by doppelgrau** [comment]
Thanks for spotting, yes, all one row off.
Copy & Paste error after last update the part list.
