### ISSUE TITLE
Rotate PCB Labels

### ISSUE THREAD

**Issue by flywire** [doppelgrau/esp32-f9p-io-board#28]
The following labels are inverted relative to others:
- ESP-F9P-IO-Board
- Version 2.2
- GND / 12V / M1A / M1B
- Uart / RX / TX

**Comment by doppelgrau** [comment]
Done on purpose.
Assumes mounting with the antenna on top might be likely => easier to read

**Comment by flywire** [comment]
A linked built photo would demonstrate.

**Comment by doppelgrau** [comment]
Currently work in progress :)

**Comment by doppelgrau** [comment]
![photo_2019-10-08_18-01-51](https://user-images.githubusercontent.com/6315907/66784239-2a366580-eeda-11e9-9590-7a8ca68aea58.jpg)
Foto from the previous version before rotating the writing. looks wrong when mounted with the cables pointing down (less dust enters case)

**Comment by flywire** [comment]
Clearly demonstrated. An easy rotate all labels command would have been nice.
